app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
| Route Model Binding defined in RouteServiceProvider Class
|
*/

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);


Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

/**
 *
 * Categories Routes
**/

// view inactive/trashed categories
Route::get('categories/inactive', ['as' => 'categories.indexInactive', 'uses' => 'CategoriesController@indexInactive']);

// deactivate/trash categories
Route::get('categories/{categories}/deactivate', ['as' => 'categories.deactivate', 'uses' => 'CategoriesController@softDelete']);

// activate trashed categories
Route::get('categories/{categories}/activate', ['as' => 'categories.activate', 'uses' => 'CategoriesController@softStore']);

// creates RESTFUL routes
Route::resource('categories', 'CategoriesController');

/**
 *
 * Accounts Routes
 **/
// view inactive/trashed fixed transactions
Route::get('accounts/inactive', ['as' => 'accounts.indexInactive', 'uses' => 'AccountsController@indexInactive']);

// deactivate/trash fixed transactions
Route::get('accounts/{accounts}/deactivate', ['as' => 'accounts.deactivate', 'uses' => 'AccountsController@softDelete']);

// activate trashed fixed transactions
Route::get('accounts/{accounts}/activate', ['as' => 'accounts.activate', 'uses' => 'AccountsController@softStore']);

// creates RESTFUL routes
Route::resource('accounts', 'AccountsController');

/**
 *
 * Fixed transactions Routes
 **/
// Create the monthly fixed transactions into transactions (for use with cron)
Route::get('fixed-transactions/sync-cron', 'FixedTransactionsController@generateMonthlyFixedTransactionsCron');

// Create the monthly fixed transactions into transactions 
Route::get('fixed-transactions/sync', ['as' => 'fixed-transactions.sync', 'uses' => 'FixedTransactionsController@generateMonthlyFixedTransactions']);

// view inactive/trashed fixed transactions
Route::get('fixed-transactions/inactive', ['as' => 'fixed-transactions.indexInactive', 'uses' => 'FixedTransactionsController@indexInactive']);

// deactivate/trash fixed transactions
Route::get('fixed-transactions/{fixed_transactions}/deactivate', ['as' => 'fixed-transactions.deactivate', 'uses' => 'FixedTransactionsController@softDelete']);

// activate trashed fixed transactions
Route::get('fixed-transactions/{fixed_transactions}/activate', ['as' => 'fixed-transactions.activate', 'uses' => 'FixedTransactionsController@softStore']);

// creates RESTFUL routes
Route::resource('fixed-transactions', 'FixedTransactionsController');


/**
 *
 * Transactions Routes
 **/
// creates RESTFUL routes
Route::resource('expenses', 'ExpensesController');
Route::resource('incomes', 'IncomesController');
Route::resource('transfers', 'TransfersController');

/**
 *
 * Statistics Routes
 **/
Route::get('statistics', ['as' => 'statistics', 'uses' => 'StatisticsController@index']);

/**
 *
 * API Routes
**/
// Get the user's category by type in json format
Route::get('api/categories/type/{type_id}', 'CategoriesController@getUserCategoriesByType');

// Get the user's transactions in json format
Route::get('api/transactions', 'IncomesController@getTransactions');

resources/views/home.blade.php
@extends('layout')
@section('content')

@if ($user)

    <div class="page-header">
        <h1>Mis Cuentas</h1>
    </div>

    @if (!count($categories))
        <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Atención!</strong> Aún no tienes categorias. Crea una <a href="{{ route('categories.create') }}">Aquí</a>.
        </div>
    @endif

    @if (!count($accounts))
        <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Atención!</strong> Aún no tienes cuentas. Crea una <a href="{{ route('accounts.create') }}">Aquí</a>.
        </div>
    @endif

    <div class="panel panel-primary">
        <!-- Default panel contents -->
        <div class="panel-heading">Acciones</div>
        <div class="panel-body">
            <a class="btn btn-danger" href="{{ route('expenses.create') }}" role="button"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span> Crear Gasto</a>
            <a class="btn btn-success" href="{{ route('incomes.create') }}" role="button"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Crear Ingreso</a>
            <a class="btn btn-default" href="{{ route('transfers.create') }}" role="button"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Crear Transferencia</a>

            {!! Form::open(['url' => '/', 'method' => 'GET', 'class' => 'navbar-form pull-right', 'role' => 'search']) !!}
                <div class="input-group">
                    {!! Form::input('text','search', null, ['class'=>'form-control', 'placeholder' => 'Buscar']) !!}
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
                </div>
            {!! Form::close() !!}

        </div>

    </div>

    <div class="panel panel-primary">
        <!-- Default panel contents -->
        <div class="panel-heading">Resumen global</div>
        <div class="panel-body">
            <p><span class="label label-success">Débito Total:</span> ${{ $total_debit_formatted }} <span class="label label-danger">Crédito Total:</span> ${{ $total_credit_formatted }}</p>
        </div>
    </div>

    @if (count($transactions))

        @foreach ($transactions as $key => $transactions_month)

            <div class="page-header">
                <h3>{{ $key }}</h3>

                @if (count($accounts))

                    <div class="accounts-info">
                        @foreach($accounts as $account)

                            @if($account->type_id == config('constants.ACCOUNT_TYPE_INDEX.debit') || $account->type_id == config('constants.ACCOUNT_TYPE_INDEX.cash'))
                                <span class="label label-success">{{ $account->title }}:</span>
                            @else
                                <span class="label label-danger">{{ $account->title }}:</span>
                            @endif

                             ${{ number_format($account->getTotalAmount($account->id, $transactions_month->first()->published_date), 0, '.', '.') }}

                        @endforeach
                    </div>

                @endif

                @if (count($transactions_month->first()->getGeneralStatistic()))

                    <div class="transactions-info">
                        <span class="label label-success">Ingresos:</span> ${{ number_format($transactions_month->first()->getGeneralStatistic()->total_amount_incomes, 0, '.', '.') }}
                        <span class="label label-danger">Gastos:</span> ${{ number_format($transactions_month->first()->getGeneralStatistic()->total_amount_expenses, 0, '.', '.') }}
                    </div>

                @endif
                
            </div>

            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Tipo</th>
                        <th>Categoria</th>
                        <th>Monto</th>
                        <th>Pagado con</th>
                        <th>Fecha de Pago</th>
                        <th>Fecha límite de pago</th>
                        <th>Acción</th>
                    </tr>
                    </thead>
                    <tbody>

                        @foreach ($transactions_month as $transaction)

                            @if (is_null($transaction->paid_date))
                                @if($transaction->payment_date_limit &&
                                    ($transaction->payment_date_limit->diff(Date::now())->days < 3 || $transaction->payment_date_limit < Date::now()))
                                    <tr class="extreme-danger">
                                @else
                                    <tr class="warning">
                                @endif
                            @elseif ($transaction->type_id == config('constants.TYPE_INDEX.expense'))
                                <tr class="danger">
                            @elseif ($transaction->type_id == config('constants.TYPE_INDEX.income'))
                                <tr class="success">
                            @else
                                <tr>
                            @endif
                                <td>{{ $transaction->title }}</td>
                                <td>{{ $transaction->getType() }}</td>
                                <td>{{ $transaction->category->title }}</td>
                                <td>{{ $transaction->present()->amount_paid_formatted }}</td>
                                <td>{{ $transaction->getAccount() }}</td>
                                <td>{{ $transaction->present()->paid_date_formatted }}</td>
                                <td>{{ $transaction->present()->payment_date_limit_formatted }}</td>
                                <td> 
                                <?php switch ($transaction->type_id) {
                                    case config('constants.TYPE_INDEX.expense'):
                                        $controlador = 'expenses';
                                        break;
                                    case config('constants.TYPE_INDEX.income'):
                                        $controlador = 'incomes';
                                        break;                                    
                                    case config('constants.TYPE_INDEX.transfer'):
                                        $controlador = 'transfers';
                                        break; 
                                } ?>
                                @if ($transaction->type_id == config('constants.TYPE_INDEX.expense'))
                                    <a alt="Editar" title="Editar" href="{{ route('expenses.edit', $transaction) }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                                    {!! Form::model($transaction, ['method' => 'DELETE', 'action' => ['ExpensesController@destroy', $transaction], 'id' => 'delete' . $transaction->id, 'class' => 'delete']) !!}
                                 
                                @elseif ($transaction->type_id == config('constants.TYPE_INDEX.income'))
                                    <a alt="Editar" title="Editar" href="{{ route('incomes.edit', $transaction) }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>      
                                    {!! Form::model($transaction, ['method' => 'DELETE', 'action' => ['IncomesController@destroy', $transaction], 'id' => 'delete' . $transaction->id, 'class' => 'delete']) !!}
                                           
                                @elseif ($transaction->type_id == config('constants.TYPE_INDEX.transfer'))
                                    <a alt="Editar" title="Editar" href="{{ route('transfers.edit', $transaction) }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                                    {!! Form::model($transaction, ['method' => 'DELETE', 'action' => ['TransfersController@destroy', $transaction], 'id' => 'delete' . $transaction->id, 'class' => 'delete']) !!}
                                 
                                @endif
                                        <a href="javascript:;" onclick="document.getElementById('delete{{ $transaction->id }}').submit();" title="Borrar permanentemente"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                                    {!! Form::close() !!}  
                                </td>
                            </tr>

                        @endforeach

                    </tbody>
                </table>
            </div>

        @endforeach
    @endif

@else
    <div id="bienvenida" class="jumbotron">
        <h1>Bienvenido a miscuentas.online!</h1>
        <p>Mis Cuentas Online es un sistema de contabilidad personal totalmente gratuito.</p>
        <p>Registra la contabilidad de tus gastos e ingresos al igual que el balance de tus cuentas.</p>
        <p>Cuenta con varios gráficos que te permiten visualizar en qué gastas tu dinero.</p>
        <p><a class="btn btn-primary btn-lg" href="auth/register" role="button">Regístrate aquí</a></p>
    </div>
@endif

@stop

resources/views/layout.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Mis Cuentas Online</title>

    <meta name=viewport content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{{ elixir('css/all.css') }}" >

	@yield('header')

</head>
<body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Mis Cuentas Online</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
              <li>
                  <a href="{{ route('expenses.index') }}" class="dropdown-toggle disabled" data-toggle="dropdown" role="button" aria-haspopup="true">
                      Gastos
                      <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                      <li><a href="{{ route('expenses.index') }}">Ver Gastos</a></li>
                      <li role="separator" class="divider"></li>
                      <li><a href="{{ route('expenses.create') }}">Crear Gasto</a></li>
                  </ul>
              </li>
              <li>
                  <a href="{{ route('incomes.index') }}" class="dropdown-toggle disabled" data-toggle="dropdown" role="button" aria-haspopup="true">
                      Ingresos
                      <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                      <li><a href="{{ route('incomes.index') }}">Ver Ingresos</a></li>
                      <li role="separator" class="divider"></li>
                      <li><a href="{{ route('incomes.create') }}">Crear Ingreso</a></li>
                  </ul>
              </li>
              <li>
                  <a href="{{ route('transfers.index') }}" class="dropdown-toggle disabled" data-toggle="dropdown" role="button" aria-haspopup="true">
                      Transferencias
                      <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                      <li><a href="{{ route('transfers.index') }}">Ver Transferencias</a></li>
                      <li role="separator" class="divider"></li>
                      <li><a href="{{ route('transfers.create') }}">Crear Transferencia</a></li>
                  </ul>
              </li>
              <li>
                  <a href="{{ route('fixed-transactions.index') }}" class="dropdown-toggle disabled" data-toggle="dropdown" role="button" aria-haspopup="true">
                      Transacciones Fijas
                      <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                      <li><a href="{{ route('fixed-transactions.index') }}">Ver Transacciónes Fijas</a></li>
                      <li><a href="{{ route('fixed-transactions.indexInactive') }}">Ver Transacciónes Fijas Inactivas</a></li>
                      <li role="separator" class="divider"></li>
                      <li><a href="{{ route('fixed-transactions.create') }}">Crear Transacción Fija</a></li>
                  </ul>
              </li>
              <li>
                  <a href="{{ route('accounts.index') }}" class="dropdown-toggle disabled" data-toggle="dropdown" role="button" aria-haspopup="true">
                      Cuentas
                      <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                      <li><a href="{{ route('accounts.index') }}">Ver Cuentas</a></li>
                      <li><a href="{{ route('accounts.indexInactive') }}">Ver Cuentas Inactivas</a></li>
                      <li role="separator" class="divider"></li>
                      <li><a href="{{ route('accounts.create') }}">Crear Cuenta</a></li>
                  </ul>
              </li>
              <li>
                  <a href="{{ route('categories.index') }}" class="dropdown-toggle disabled" data-toggle="dropdown" role="button" aria-haspopup="true">
                      Categorias
                      <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                      <li><a href="{{ route('categories.index') }}">Ver Categorias</a></li>
                      <li><a href="{{ route('categories.indexInactive') }}">Ver Categorias Inactivas</a></li>
                      <li role="separator" class="divider"></li>
                      <li><a href="{{ route('categories.create') }}">Crear Categoria</a></li>
                  </ul>
              </li>
              <li><a href="/statistics">Estadísticas</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <li class="active">
                  @if($user)
                      <a href="#" class="dropdown-toggle disabled" data-toggle="dropdown" role="button" aria-haspopup="true">
                          <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                          {{ $user->name }}
                          <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu">
                          <li><a href="#">Mi Cuenta</a></li>
                          <li role="separator" class="divider"></li>
                          <li><a href="/auth/logout"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Salir</a></li>
                      </ul>
                  @else
                     <a href="/auth/login"><span class="glyphicon glyphicon-user" aria-hidden="true"></span><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> Ingresar</a>
                  @endif
              </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

	<div class="container">
        @if (Session::has('flash_message'))
            <div class="alert alert-{{ Session::get('flash_action') }}">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ Session::get('flash_message') }}
            </div>
        @endif

		@yield('content')
	</div>

	@yield('footer')

    <footer class="footer">
        <div class="container">
            <p class="text-muted">2016 - Aplicación web creada por <a href="http://franciscogiraldo.com" target="_blank">Francisco Giraldo</a> </p>
        </div>
    </footer>

	<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
	<script type="text/javascript" src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

    <script>
        //enable nav dropdown menu on hover
        $(function() {
            $('.nav li').hover(function(){
                $(this).addClass('open');
            }, function(){
                $(this).removeClass('open');
            });
        });

    </script>

    @yield('javascript')

</body>
</html>

resources/views/search.blade.php
@extends('layout')
@section('content')

    <div class="page-header">
        <h1>Búsqueda</h1>
    </div>

    <div class="panel panel-primary">
        <!-- Default panel contents -->
        <div class="panel-heading">Acciones</div>
        <div class="panel-body">

            {!! Form::open(['url' => '/', 'method' => 'GET', 'class' => 'navbar-form pull-right', 'role' => 'search']) !!}
                <div class="input-group">
                    {!! Form::input('text','search', null, ['class'=>'form-control', 'placeholder' => 'Buscar']) !!}
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
                </div>
            {!! Form::close() !!}

        </div>

    </div>

    <div class="panel panel-primary">
        <!-- Default panel contents -->
        <div class="panel-heading">Resumen global</div>
        <div class="panel-body">
            <p><span class="label label-success">Ingresos:</span> ${{ number_format($balance['incomes'], 0, '.', '.') }} <span class="label label-danger">Gastos:</span> ${{ number_format($balance['expenses'], 0, '.', '.') }}</p>
        </div>
    </div>

    @if (count($transactions))

        @foreach ($transactions as $key => $transactions_month)

            <div class="page-header">
                <h3>{{ $key }}</h3>
            </div>

            <?php $monthly_balance = Transaction::calculateIncomesExpenses($transactions_month); ?>

            <div class="transactions-info">
                <span class="label label-success">Ingresos:</span> ${{ number_format($monthly_balance['incomes'], 0, '.', '.') }}
                <span class="label label-danger">Gastos:</span> ${{ number_format($monthly_balance['expenses'], 0, '.', '.') }}
            </div>

            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Tipo</th>
                        <th>Categoria</th>
                        <th>Monto</th>
                        <th>Pagado con</th>
                        <th>Fecha de Pago</th>
                        <th>Fecha límite de pago</th>
                        <th>Acción</th>
                    </tr>
                    </thead>
                    <tbody>

                        @foreach ($transactions_month as $transaction)

                            @if (is_null($transaction->paid_date))
                                @if($transaction->payment_date_limit &&
                                    ($transaction->payment_date_limit->diff(Date::now())->days < 3 || $transaction->payment_date_limit < Date::now()))
                                    <tr class="extreme-danger">
                                @else
                                    <tr class="warning">
                                @endif
                            @elseif ($transaction->type_id == config('constants.TYPE_INDEX.expense'))
                                <tr class="danger">
                            @elseif ($transaction->type_id == config('constants.TYPE_INDEX.income'))
                                <tr class="success">
                            @else
                                <tr>
                            @endif
                                <td>{{ $transaction->title }}</td>
                                <td>{{ $transaction->getType() }}</td>
                                <td>{{ $transaction->category->title }}</td>
                                <td>{{ $transaction->present()->amount_paid_formatted }}</td>
                                <td>{{ $transaction->getAccount() }}</td>
                                <td>{{ $transaction->present()->paid_date_formatted }}</td>
                                <td>{{ $transaction->present()->payment_date_limit_formatted }}</td>
                                <td> 
                                <?php switch ($transaction->type_id) {
                                    case config('constants.TYPE_INDEX.expense'):
                                        $controlador = 'expenses';
                                        break;
                                    case config('constants.TYPE_INDEX.income'):
                                        $controlador = 'incomes';
                                        break;                                    
                                    case config('constants.TYPE_INDEX.transfer'):
                                        $controlador = 'transfers';
                                        break; 
                                } ?>
                                @if ($transaction->type_id == config('constants.TYPE_INDEX.expense'))
                                    <a alt="Editar" title="Editar" href="{{ route('expenses.edit', $transaction) }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                                    {!! Form::model($transaction, ['method' => 'DELETE', 'action' => ['ExpensesController@destroy', $transaction], 'id' => 'delete' . $transaction->id, 'class' => 'delete']) !!}
                                 
                                @elseif ($transaction->type_id == config('constants.TYPE_INDEX.income'))
                                    <a alt="Editar" title="Editar" href="{{ route('incomes.edit', $transaction) }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>      
                                    {!! Form::model($transaction, ['method' => 'DELETE', 'action' => ['IncomesController@destroy', $transaction], 'id' => 'delete' . $transaction->id, 'class' => 'delete']) !!}
                                           
                                @elseif ($transaction->type_id == config('constants.TYPE_INDEX.transfer'))
                                    <a alt="Editar" title="Editar" href="{{ route('transfers.edit', $transaction) }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                                    {!! Form::model($transaction, ['method' => 'DELETE', 'action' => ['TransfersController@destroy', $transaction], 'id' => 'delete' . $transaction->id, 'class' => 'delete']) !!}
                                 
                                @endif
                                        <a href="javascript:;" onclick="document.getElementById('delete{{ $transaction->id }}').submit();" title="Borrar permanentemente"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                                    {!! Form::close() !!}  
                                </td>
                            </tr>

                        @endforeach

                    </tbody>
                </table>
            </div>

        @endforeach
    @endif

@stop